config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games

  resources :shows

  resources :sports

  resources :news

  get 'pages/index'
  get 'pages/team'
  get 'pages/svg'
  get 'pages/home'
  get 'pages/contact'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users

  root 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InfoPrisma</title>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Basic -->
  <meta charset="utf-8">
  <meta name="keywords" content="motor, toyota, atodomotorweb, beach, gts, atodomotor"/>
  <meta name="description" content="Mantenete informado sobre sobre nuestras actividades. Seguinos. Contactos comerciales. comercial@atodomotorweb.com. A Todo Motor.">

  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Web Fonts  -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Alegreya|Alegreya+SC|Oswald:400,300" rel="stylesheet" type="text/css">

  <!-- Favicon  -->
  <link rel="shortcut icon" type="image/png" href="/assets/favicon.png"/>

  <!-- Libs CSS -->
  <link rel="stylesheet" href="/assets/bootstrap.css">
  <link rel="stylesheet" href="/assets/fonts/font-awesome/css/font-awesome.css">
  <link rel="stylesheet" href="/assets/vendor/owl-carousel/owl.carousel.css" media="screen"/>
  <link rel="stylesheet" href="/assets/vendor/owl-carousel/owl.theme.css" media="screen"/>
  <link rel="stylesheet" href="/assets/vendor/rs-plugin/css/settings.css" media="screen"/>
  <link rel="stylesheet" href="/assets/vendor/isotope/jquery.isotope.css" media="screen"/>
  <link rel="stylesheet" href="/assets/vendor/magnific-popup/magnific-popup.css" media="screen"/>

  <!-- Theme CSS -->
  <link rel="stylesheet" href="/assets/theme.css">
  <link rel="stylesheet" href="/assets/theme-elements.css">
  <link rel="stylesheet" href="/assets/theme-animate.css">

  <!-- Skin CSS -->
  <link rel="stylesheet" href="/assets/skins/default.css">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="/assets/custom.css">

  <!-- Responsive CSS -->
  <link rel="stylesheet" href="/assets/theme-responsive.css"/>

  <!-- Head Libs -->

  <script src="/assets/application.js"></script>
  <script src="/assets/tabs_active.js"></script>
  <script src="/assets/vendor/modernizr.js"></script>
  <script src="/assets/custom.js"></script>
  <script src="https://www.youtube.com/iframe_api"></script>

  <!--[if IE]>
  <link rel="stylesheet" href="/assets/ie.css">
  <![endif]-->

</head>
<body>


<div class="body">
<header>
  <div class="container">
    <h1 class="logo">
      <a href="<%= root_path %>">
        <img alt="" src="/assets/logos/logo_mini.png" data-small-height="44">
      </a>
    </h1>

    <div class="navbar-collapse nav-main-collapse collapse">
      <!--<div class="search" id="headerSearch">-->
        <!--<a href="#" id="headerSearchOpen"><i class="icon icon-search"></i></a>-->

        <!--<div class="search-input">-->
          <!--<form id="headerSearchForm"  method="get">-->
            <!--<div class="input-group">-->
              <!--<input type="text" class="form-control search" name="q" id="q" placeholder="Buscar...">-->
										<!--<span class="input-group-btn">-->
											<!--<button class="btn btn-primary" type="button">-->
                                              <!--<i class="icon icon-search"></i></button>-->
										<!--</span>-->
            <!--</div>-->
          <!--</form>-->
        <!--</div>-->
      <!--</div>-->
      <nav class="nav-main mega-menu">
        <ul class="nav nav-pills nav-main" id="mainMenu">

          <li id="home" class="active">
            <a href="<%= root_path %>">
              Principal
            </a>
          </li>



          <li id="team">
            <a href="<%= pages_team_url %>">
              El equipo
            </a>
          </li>

          <% if current_user %>
          <li id="user" class="dropdown">
            <a class="dropdown-toggle" href="#">
              Mi Perfíl
              <i class="icon icon-user"></i>
            </a>


            <ul class="dropdown-menu">
              <li><a href="<%=user_path(current_user)%>">Perfíl</a></li>
              <li><%= link_to 'Salir', destroy_user_session_path, :method => :delete %></li>

            </ul>
          </li>
                <%else%>

              <li><a href="<%=users_path%>">Registrate</a></li>

                <%end%>

          <li id="contact">
            <a href="<%= pages_contact_url %>">
              Contacto
            </a>
          </li>

          <li>
            <a href="https://www.facebook.com/" target="_blank" rel="tooltip" title="" data-original-title="Facebook">
              <img src="/assets/social/face_icon.png" alt="" width="25"/>
            </a>
          </li>
          <li>
            <a href="https://twitter.com/" target="_blank" rel="tooltip" title="" data-original-title="Twitter">
              <img src="/assets/social/twitter_icon.png" alt="" width="25"/>
            </a>
          </li>

        </ul>
      </nav>
    </div>
    <button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
      <i class="icon icon-bars"></i>
    </button>

  </div>
</header>


<div role="main" class="main">


  <%= yield %>
</div>


<footer id="footer" style="padding-top: 5px">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-6" style="margin-bottom: 0px;">
          <a href="<%= root_path %>" class="logo push-bottom">
            <img alt="InfoPrisma" src="/assets/logos/logo_prisma.png" style="height: 70px;">
          </a>
        </div>
        <div class="col-md-6" style="margin-bottom: 15px;">
          <ul class="social-icons">
            <li>
              <a href="https://twitter.com/" target="_blank" rel="tooltip" title="" data-original-title="Twitter">
                <img src="/assets/social/face_icon.png" alt="" width="35"/>
              </a>
            </li>
            <li>
              <a href="https://twitter.com/" target="_blank" rel="tooltip" title="" data-original-title="Twitter">
                <img src="/assets/social/twitter_icon.png" alt="" width="35"/>
              </a>
            </li>
            <li></li>
          </ul>
        </div>
        <p style="text-align: right">Copyright © 2014<a href="http://www.atodomotorweb.com"> InfoPrisma</a>.

      </div>
    </div>
  </div>
</footer>
</div>

<!-- Libs -->


<script src="/assets/vendor/jquery.js"></script>
<script src="/assets/plugins.js"></script>
<script src="/assets/vendor/jquery.easing.js"></script>
<script src="/assets/vendor/jquery.appear.js"></script>
<script src="/assets/vendor/jquery.cookie.js"></script>

<script src="/assets/vendor/bootstrap.js"></script>
<script src="/assets/vendor/masonry.js"></script>
<script src="/assets/vendor/twitterjs/twitter.js"></script>
<script src="/assets/vendor/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
<script src="/assets/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script src="/assets/vendor/owl-carousel/owl.carousel.js"></script>
<script src="/assets/vendor/magnific-popup/magnific-popup.js"></script>
<script src="/assets/vendor/jquery.knob.js"></script>
<script src="/assets/vendor/jquery.stellar.js"></script>
<script src="/assets/vendor/jquery.validate.js"></script>
<script src="/assets/vendor/isotope/jquery.isotope.js"></script>

<!-- Current Page Scripts -->
<script src="/assets/views/view.home.js"></script>

<!-- Theme Initializer -->
<script src="/assets/theme.js"></script>

<!-- Custom JS -->
<script src="/assets/custom.js"></script>

<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="/assets/vendor/jquery.gmap.js"></script>
<script src="/assets/mapStyle.js"></script>


<!--<script src="/assets/pagination.js.coffee"></script>-->


</body>
</html>